- hosts: localhost
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude

    - name: Add PPAs
      apt_repository:
        repo: "{{ item }}"
      loop:
        - "ppa:git-core/ppa"
        - "ppa:papirus/papirus"
        - "ppa:tista/plata-theme"
        - "ppa:christian-boxdoerfer/fsearch-daily"

    - name: Install basic packages
      apt:
        name:
          - openjdk-8-jdk
          - software-properties-common

    - name: Install commandline packages
      apt:
        name:
          - aptitude
          - curl
          - git # Requires PPA
          - htop
          - jq
          - neofetch
          - pandoc
          - rclone
          - scrcpy

    - name: Install GUI packages
      apt:
        name:
          - barrier
          - evince
          - firefox
          - fonts-cmu
          - ibus-rime
          - papirus-icon-theme # Requires PPA
          - plata-theme # Requires PPA
          - qdirstat
          - tldr
          - tuptime
          - usb-creator-gtk
          - fsearch-trunk # Requires PPA

    - name: Remove unused packages
      apt:
        name:
          - deja-dup
          - nautilus
          - magnus
          - byobu
        state: absent
