- hosts: localhost
  become: true
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude

    - name: Add PPAs
      apt_repository:
        repo: "{{ item }}"
      loop:
        - ppa:papirus/papirus
        - ppa:tista/plata-theme
        - ppa:christian-boxdoerfer/fsearch-daily
        - deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe
        - deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} multiverse
        - deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} restricted

    - name: Install basic packages
      apt:
        name:
          - openjdk-8-jdk
          - software-properties-common

    - name: Install commandline packages
      apt:
        name:
          - aptitude
          - bat
          - curl
          - fd-find
          - ffmpeg
          - fzf
          - git
          - htop
          - jq
          - kakoune
          - micro
          - neofetch
          - pandoc
          - rclone
          - restic
          - scrcpy
          - tldr
          - tuptime
          - youtube-dl

    - name: Install GUI packages
      apt:
        name:
          - barrier
          - epiphany-browser 
          - evince
          - firefox
          - flameshot
          - fonts-cmu
          - fsearch-trunk # Requires PPA
          - papirus-icon-theme
          - plata-theme # Requires PPA
          - qdirstat
          - usb-creator-gtk

    - name: Remove unused packages
      apt:
        name:
          - byobu
          - deja-dup
          - magnus
          - nautilus
        state: absent
