- hosts: localhost
  become: true
  tasks:
    - name: Add fish PPA
      apt_repository:
        repo: "ppa:fish-shell/release-3"

    - name: Install fish
      apt:
        name: fish

    - name: Set default shell to fish
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/fish

    - name: Create directory for fisher install script
      file:
        path: /opt/fisher/
        state: directory

    - name: Get the username running the deploy
      become: false
      local_action: command whoami
      register: my_user
    
    - name: Install fisher plugin manager
      get_url:
        url: https://git.io/fisher
        dest: "/home/{{ my_user.stdout }}/.config/fish/functions/fisher.fish"
        force: true

    - name: Change default shell to fish 
      become: yes
      user:
        name: "{{ my_user.stdout }}"
        shell: /usr/bin/fish

    - name: Install fzf
      apt:
        name: fzf

    # - name: Update fisher
    #   command: "fish -c 'fisher install jorgebucaran/fisher'"
