- hosts: localhost
  become: true
  environment:
    XDG_DATA_DIRS: /usr/share:$HOME/.local/share/flatpak/exports/share:/var/lib.flatpak/exports/share
  tasks:
    - name: Install flatpak
      apt:
        name:
          - flatpak

    - name: Integrate with gnome software
      apt:
        name:
          - gnome-software-plugin-flatpak

    - name: Add flatpak remotes
      community.general.flatpak_remote:
        name: "{{ item.key }}"
        state: present
        flatpakrepo_url: "{{ item.value }}"
      loop: "{{ remotes | dict2items }}"
      vars:
        remotes:
          flathub: https://flathub.org/repo/flathub.flatpakrepo
          flathub-beta: https://flathub.org/beta-repo/flathub-beta.flatpakrepo
          kdeapps: https://distribute.kde.org/kdeapps.flatpakrepo

    - name: Install flatpaks from flathub
      community.general.flatpak:
        name: "{{ item }}"
      loop:
        - com.github.johnfactotum.Foliate # Foliate
        - com.github.PintaProject.Pinta # Pinta
        - com.github.tchx84.Flatseal # Flatseal
        - com.obsproject.Studio # OBS Studio
        - com.spotify.Client # Spotify
        - im.riot.riot # Element
        - io.dbeaver.DBeaverCommunity # DBeaver CE
        - net.ankiweb.Anki # Anki
        - org.audacityteam.Audacity # Audacity
        - org.blender.Blender # Blender
        - org.flameshot.Flameshot # Flameshot
        - org.glimpse_editor.Glimpse # Glimpse
        - org.gnome.eog # Eye of Gnome
        - org.gnome.gitlab.YaLTeR.VideoTrimmer # VideoTrimmer
        - org.gnome.GTG # Getting Things Gnome
        - org.gpodder.gpodder # gPodder
        - org.gtk.Gtk3theme.Plata-Noir/x86_64/3.24 # Plata Noir
        - org.inkscape.Inkscape # Inskscape
        - org.kde.kdenlive # Kdenlive
        - org.kde.krita # Krita
        - org.libreoffice.LibreOffice # LibreOffice
        - org.musescore.MuseScore # Musescore
        - org.qbittorrent.qBittorrent # qBittorrent
        - org.signal.Signal # Signal
        - org.telegram # Telegram
        - org.zulip.Zulip # Zulip
