- hosts: localhost
  become: true
  tasks:
    - name: Add nvidia repository
      apt_repository:
        repo: ppa:graphics-drivers/ppa

    - name: Install drivers
      apt:
        name:
          - nvidia-driver-460
          - libnvidia-gl-460:i386
          - libvulkan1
          - libvulkan1:i386
