- hosts: localhost
  become: true
  tasks:
    - name: Install Python apt packages
      apt:
        name:
          - python3
          - python3-venv
          - python3-pip
          - libpq-dev
          - python3-dev
          - python3-tk
          - python3-gi
          - python3-apt
