- hosts: localhost
  become: true
  tasks:
    - name: Install Python
      apt:
        name:
          - python3
         
    - name: Install related python packages
      apt:
        name:
          - python3-apt
          - python3-dev
          - python3-gi
          - python3-pip
          - python3-tk
          - python3-venv
          - libpq-dev
