- hosts:  localhost
  roles:
    - r
  vars:
    r_install_dev: true
    r_install:
      - build-essential
      - gdebi-core
      - git-core
      - libapparmor1
      - libcairo2-dev
      - libcurl4-gnutls-dev
      - libssl-dev
      - libxml2-dev
      - libxt-dev
      - littler
      - r-base
      - r-base-core
      - r-base-dev
      - r-recommended
    r_packages:
      - DBI
      - dplyr
      - ggplot2
      - haven
      - here
      - knitr
      - lubridate
      - magrittr
      - rmarkdown
      - scales
      - shiny
      - tidyr
      - tidyverse
      - zoo

  # tasks:
  #   - name: Add GPG key
  #     # Check if it has changed here: https://cran.r-project.org/bin/linux/ubuntu/README.html
  #     apt_key:
  #       id: "0x51716619e084dab9"
  #       keyserver: hkp://keyserver.ubuntu.com:80

  #   - name: Add PPA
  #     apt_repository:
  #       # repo: "deb http://cran.rstudio.com/bin/linux/ubuntu {{ ansible_distribution_release }}-cran35/"
  #       repo: "deb http://cran.rstudio.com/bin/linux/ubuntu eoan-cran35/"

  #   - name: Install R
  #     apt:
  #       name:
  #         - r-base
  #         - r-base-core
  #         - r-base-dev
  #         - libapparmor1
  #         - libcurl4-gnutls-dev
  #         - libxml2-dev
  #         - libssl-dev
  #         - gdebi-core
  #         - libcairo2-dev
  #         - libxt-dev
  #         - git-core
  #         - build-essential

  #   - name: Install R packages
  #     cran:
  #       name: "{{ item }}"
  #     loop:
  #       - ggplot2
  #       - magrittr
  #       - tidyr
  #       - dplyr`
  #       - tidyverse
  #       - here
  #       - shiny
  #       - scales
  #       - zoo
  #       - knitr
  #       - DBI
  #       - haven
  #       - lubridate
  #       - rmarkdown
