- hosts: localhost
  become: true
  tasks:
    - name: Install snaps with normal confinement
      snap:
        name:
          - bitwarden
        classic: false

    - name: Remove unused snaps
      snap:
        name: ubuntu-budgie-welcome
