- hosts: localhost
  become: true
  tasks:
    - name: Install Bitwarden
      snap:
        name:
          - bitwarden
        classic: false

    - name: Install Onefetch
      snap:
        name: onefetch

    - name: Remove unused snaps
      snap:
        name: ubuntu-budgie-welcome
        state: absent
