- hosts: localhost
  become: true
  tasks:
    - name: Install snaps with normal confinement
      snap:
        name:
          - bitwarden
          - chromium
          - discord
          - ffmpeg
          - htop
          - jq
          - onefetch
          - vlc
        classic: false

    - name: Install snaps with classic confinement
      snap:
        name: "{{ item }}"
        classic: true
      loop:
        - kakuone
        - micro
        - restic
