- hosts: localhost
  become: true
  tasks:
    - name: Set Alacritty as default
      community.general.alternatives:
        name: x-terminal-emulator
        path: /home/hannes/bin/alacritty

    - name: Remove Gnome Terminal
      apt:
        name: gnome-terminal
        state: absent

    - name: Install Micro text editor
      apt:
        name: micro
