- hosts: localhost
  become: true
  tasks:
    - name: Install Kitty
      apt:
        name: kitty

    - name: Set Kitty as default
      community.general.alternatives:
        name: x-terminal-emulator
        path: /usr/bin/kitty

    - name: Remove Gnome Termial
      apt:
        name: gnome-terminal
        state: absent

    - name: Install Micro text editor
      snap:
        name: micro
        classic: true
