- hosts: localhost
  become: true
  tasks:
    - name: Add terraform GPG key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg

    - name: Add terraform repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"

    - name: Install terraform
      apt:
        name: terraform
